name: hauk
base: core24
version: '1.6.2'
summary: Open-source realtime location sharing
description: |
  Hauk is a fully open source, self-hosted location sharing service.

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

layout:
  /etc/apache2:
    symlink: $SNAP/etc/apache2
  /etc/hauk:
    symlink: $SNAP_DATA/etc
  /etc/php:
    symlink: $SNAP/etc/php
  /usr/lib/apache2:
    symlink: $SNAP/usr/lib/apache2
  /usr/lib/php:
    symlink: $SNAP/usr/lib/php
  /usr/sbin/apache2:
    symlink: $SNAP/usr/sbin/apache2
  /usr/share/apache2:
    symlink: $SNAP/usr/share/apache2
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sasl2:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sasl2

hooks:
  configure:
    command-chain:
      - snap/command-chain/configure.sh
  install:
    command-chain:
      - snap/command-chain/install.sh
  post-refresh:
    command-chain:
      - snap/command-chain/post-refresh.sh

apps:
  apache2:
    command: bin/apache2.sh -s start
    reload-command: bin/apache2.sh -s reload
    stop-command: bin/apache2.sh -s stop
    daemon: forking
    plugs: [network, network-bind]
  memcached:
    command: bin/memcached.sh
    daemon: simple
    plugs: [network, network-bind]
  htpasswd:
    command: usr/bin/htpasswd

parts:
  local:
    plugin: dump
    source-type: local
    source: snap/local
  server:
    after: [local]
    plugin: nil
    build-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
    stage-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
      - memcached
    stage:
      - etc/apache2/
      - etc/php/
      - usr/bin/htpasswd
      - usr/bin/memcached
      - usr/bin/php8.3
      - usr/lib/apache2/
      - usr/lib/php/
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sasl2/
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.so*
      - usr/sbin/apache2
      - usr/share/apache2/
    override-prime: |
      craftctl default
      build/configure-apache2.sh
      build/configure-php.sh
  hauk:
    after: [local]
    plugin: dump
    source: https://github.com/bilde2910/Hauk/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    override-build: |
      mkdir html
      cp -a frontend/. html/
      cp -a backend-php/. html/
      craftctl default
    stage:
      - html/
    override-prime: |
      craftctl default
      patch -Ns -p0 < build/html.patch
  cleanup:
    after: [local, server, hauk]
    plugin: nil
    override-prime: |
      rm -r build/
