name: hauk
base: core24
version: '1.6.2'
summary: Open-source realtime location sharing
description: |
  Hauk is a fully open source, self-hosted location sharing service.

grade: devel
confinement: strict

layout:
  /etc/apache2:
    symlink: $SNAP/etc/apache2
  /etc/php:
    symlink: $SNAP/etc/php
  /usr/lib/apache2:
    symlink: $SNAP/usr/lib/apache2
  /usr/lib/php:
    symlink: $SNAP/usr/lib/php
  /usr/sbin/apache2:
    symlink: $SNAP/usr/sbin/apache2
  /var/apache2:
    type: tmpfs
  /var/hauk:
    symlink: $SNAP_DATA
  /var/www/html:
    symlink: $SNAP/html

system-usernames:
  snap_daemon: shared

environment:
  APACHE_RUN_USER: snap_daemon
  APACHE_RUN_GROUP: snap_daemon
  APACHE_RUN_DIR: /var/apache2/run
  APACHE_LOCK_DIR: /var/apache2/lock
  APACHE_LOG_DIR: /var/apache2/log
  APACHE_PID_FILE: /var/apache2/run/apache2.pid

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

apps:
  apache2:
    command: bin/apache2.sh
    daemon: forking
    plugs: [network, network-bind]
  memcached:
    command: bin/memcached.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  server:
    plugin: nil
    build-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
    stage-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
      - memcached
    override-prime: |
      craftctl default
      cp --remove-destination -a /etc/apache2/. etc/apache2/
      cp --remove-destination -a /etc/php/. etc/php/
      ln -sf /var/apache2/etc/ports.conf etc/apache2/ports.conf
      ln -sf /var/apache2/etc/000-default.conf etc/apache2/sites-enabled/000-default.conf
  html:
    plugin: nil
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://github.com/bilde2910/Hauk/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
      tar -xf v$SNAPCRAFT_PROJECT_VERSION.tar.gz
      mkdir html
      cp -a Hauk-$SNAPCRAFT_PROJECT_VERSION/frontend/. html/
      cp -a Hauk-$SNAPCRAFT_PROJECT_VERSION/backend-php/. html/
      cp -r html/ $CRAFT_PART_INSTALL
  local:
    after: [server, html]
    plugin: dump
    source-type: local
    source: snap/local
    override-prime: |
      craftctl default
      patch -Ns -p0 < patch/html.patch || true
