name: hauk
base: core24
version: '1.6.2'
summary: Open-source realtime location sharing
description: |
  Hauk is a fully open source, self-hosted location sharing service.

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

layout:
  /etc/apache2:
    symlink: $SNAP/etc/apache2
  /etc/hauk:
    symlink: $SNAP_DATA/etc
  /etc/php:
    symlink: $SNAP/etc/php
  /usr/lib/apache2:
    symlink: $SNAP/usr/lib/apache2
  /usr/lib/php:
    symlink: $SNAP/usr/lib/php
  /usr/sbin/apache2:
    symlink: $SNAP/usr/sbin/apache2
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sasl2:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sasl2

hooks:
  configure:
    command-chain:
      - snap/command-chain/configure.sh
  install:
    command-chain:
      - snap/command-chain/install.sh

apps:
  apache2:
    command: bin/apache2.sh -s start
    reload-command: bin/apache2.sh -s reload
    stop-command: bin/apache2.sh -s stop
    daemon: forking
    plugs: [network, network-bind]
  memcached:
    command: bin/memcached.sh
    daemon: simple
    plugs: [network, network-bind]

parts:
  server:
    after: [local]
    plugin: nil
    build-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
    stage-packages:
      - apache2
      - libapache2-mod-php
      - php8.3
      - php8.3-memcached
      - php8.3-ldap
      - memcached
    override-prime: |
      craftctl default
      bin/configure-apache2.sh
      bin/configure-php.sh
      bin/cleanup.sh
  html:
    after: [local]
    plugin: nil
    build-packages:
      - wget
      - tar
    override-build: |
      wget https://github.com/bilde2910/Hauk/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
      tar -xf v$SNAPCRAFT_PROJECT_VERSION.tar.gz
      mkdir html
      cp -a Hauk-$SNAPCRAFT_PROJECT_VERSION/frontend/. html/
      cp -a Hauk-$SNAPCRAFT_PROJECT_VERSION/backend-php/. html/
      cp -r html/ $CRAFT_PART_INSTALL
    override-prime: |
      craftctl default
      patch -Ns -p0 < patch/html.patch
  local:
    plugin: dump
    source-type: local
    source: snap/local
